Finish Project
IonutPad15/LateralTeamProject pull request #4
Opened 2022-08-09 16:17 UTC by ShaDy03

I was add class library Models with folders Request + Response
I wish delete Models.Response, but i can't.
I was finished Add-GetById-GetAll-Update-Delete on Project Table, i was testing and that's worked!

2022-08-09 16:57 UTC, iiusan requested changes

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/DataAccess/DbAccess/ISQLDataAccess.cs
> +        Task<IEnumerable<T>> LoadData<T>(string storedProcedure, string connectionId = "Default");
missing 'async' suffix

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/DataAccess/Models/Issue.cs
> +//TODO: Object FK Priority & Status & Role & Project
no unresolved TODOs in PRs

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/IssueTrackerAPI/Controllers/ProjectController.cs
> +        public async Task<List<Project>> GetAll() =>
change to IEnumerable

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/Models/Response/ProjectInfo.cs
> +            Participants = new();
why new()?

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/Models/Response/ParticipantInfo.cs
> +    public class ParticipantInfo
empty class

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/DataAccess/Data/ProjectData.cs
> +            await _db.SaveData("dbo.spProject_Insert", new { project.Title, project.Description, DateTime.Now });
use UtcNow

2022-08-09 16:57 UTC, iiusan commented on IssueTracker/DataAccess/Data/IData/IProjectData.cs
> +        Task UpdateAsync(ProjectRequest project);
no mixing between api & db dtos

2022-08-10 06:31 UTC, ShaDy03 commented on IssueTracker/DataAccess/DbAccess/ISQLDataAccess.cs
> +        Task<IEnumerable<T>> LoadData<T>(string storedProcedure, string connectionId = "Default");
can i put async in interface?

2022-08-10 06:35 UTC, ShaDy03 commented on IssueTracker/Models/Response/ProjectInfo.cs
> +            Participants = new();
i want initializer the list

2022-08-10 07:48 UTC, iiusan approved these changes

2022-08-10 07:52 UTC, merged